In [1]:
import pickle
import pandas as pd
import os
import numpy as np
from datetime import datetime

### Data Collection

Those data is collected from Estonia Weather service(https://www.ilmateenistus.ee/?lang=en) from two source : 
1. Cloud coverage data (per hour,per day)
2. Hourly weather data (per hour,per day)

Data are collected from 2019-Jan-01 to 2021-Nov-01 which come up with 24,864 individual file, after that, that two data set is join by station,date and hour to form one universe data set for data pre-processing and exploratory data analysis.

In [2]:
path='./cloudCoverageData'

#cols= ['Station','I_layer_height','I_layer_amount','II_layer_height','II_layer_amount','III_layer_height','III_layer_amount','IV_layer_height','IV_layer_amount','Vertical visibility_m','Present weather','Visibility_km','time','date']
#print(len(cols))
data=pd.DataFrame()
for x in os.listdir(path):
    print(f'Processing {x}\r',end='')
    f = open(path+'/'+x,'rb')
    filename = x.split('_')
    tmp = pickle.load(f)
    tmp['date']=filename[1]
    tmp['time']=filename[2]
    data=data.append(tmp)

In [3]:
data.columns=['Station','I_layer_height','I_layer_amount','II_layer_height','II_layer_amount','III_layer_height','III_layer_amount','IV_layer_height','IV_layer_amount','Vertical visibility_m','Present weather','Visibility_km','time2','Date']

In [308]:
f=open('./cloudCoverage_all.pickle','wb')
pickle.dump(data,f)

In [5]:
#cols=['Station','Air temperature (°C)','Relative humidity (%)','Sea level pressure (hPa)','Pressure tendency (hPa)','Wind','Wind','Wind','Cloud amount (palli)','Present weather (sensor)','Present weather (observer)','Precipitation (mm)','Visibility (km)','time','Date']
path='./hourlyData'
#print(len(cols))
i=0
data1=pd.DataFrame()
for x in os.listdir(path):
    print(f' {i} Processing {x}\r',end='')
    f = open(path+'/'+x,'rb')
    filename = x.split('_')
    tmp = pickle.load(f)
    tmp['date']=filename[1]
    tmp['time2']=filename[2]
    data1=data1.append(tmp)
    i+=1frequent count

In [6]:
data1.columns=['Station','Air temperature (°C)','Relative humidity (%)','Sea level pressure (hPa)','Pressure tendency (hPa)','Wind_Direction','Wind_Speed','Wind_gust','Cloud amount (palli)','Present weather (sensor)','Present weather (observer)','Precipitation (mm)','Visibility (km)','time','Date','time2']

In [314]:
f=open('./hourly_all.pickle','wb')
pickle.dump(data1,f)

In [56]:
dayLen=pd.read_csv('./sunrise_sunset_data.csv')
dayLen

     Month  date  Sunrise+1  Sunset-1
0        1     1         10        14
1        1     2         10        14
2        1     3         10        14
3        1     4         10        14
4        1     5         10        14
..     ...   ...        ...       ...
360     12    27         10        14
361     12    28         10        14
362     12    29         10        14
363     12    30         10        14
364     12    31         10        14

[365 rows x 4 columns]

In [100]:
#
#f=open('./hourly_cloudCoverage_join_data','rb')
#hourly_cloudCoverage_join_data=pickle.load(f)
#hourly_cloudCoverage_join_data=pd.merge(data,data1,on=['Station','Date','time2'])
#hourly_cloudCoverage_join_data['Month']=pd.DatetimeIndex(hourly_cloudCoverage_join_data['Date'],dayfirst=True).month
#hourly_cloudCoverage_join_data['date2']=pd.DatetimeIndex(hourly_cloudCoverage_join_data['Date'],dayfirst=True).day
#hourly_cloudCoverage_join_data=pd.merge(hourly_cloudCoverage_join_data,dayLen,left_on=['Month','date2'],right_on=['Month','date'])
#hourly_cloudCoverage_join_data['time2']=hourly_cloudCoverage_join_data['time2'].astype(int)
#f=open('./hourly_cloudCoverage_join_data','wb')
#pickle.dump(hourly_cloudCoverage_join_data,f)
#hourly_cloudCoverage_join_data_daytime=hourly_cloudCoverage_join_data[(hourly_cloudCoverage_join_data['time2']>=hourly_cloudCoverage_join_data['Sunrise+1']) & (hourly_cloudCoverage_join_data['time2']<=hourly_cloudCoverage_join_data['Sunset-1'])]
#hourly_cloudCoverage_join_data_nighttime=hourly_cloudCoverage_join_data[(hourly_cloudCoverage_join_data['time2']<=hourly_cloudCoverage_join_data['Sunrise+1']) & (hourly_cloudCoverage_join_data['time2']>=hourly_cloudCoverage_join_data['Sunset-1'])]

### Data Summary
The universe data set got 24 columns and 472416 rows, the following table shows a brief summary on the columns : 

|Column Name|Variable type|Description|Remark|Source|
|-----------|-------------|-----------|------|:------:|
|I_layer_height| numerical| The height of I layer(lowest) from ground (in m)|--|cloud coverage|
|II_layer_height| numerical |The height of II layer(middle) from ground (in m)|--|cloud coverage|
|III_layer_height| numerical |The height of III layer(middle) from ground (in m)|--|cloud coverage|
|IV_layer_height| numerical |The height of IV layer(His) from ground (in m)|--|cloud coverage|
|Vertical visibility|numerical| The visibility measure vertrically from groud (m)|The field got 449791 nan value,remove|cloud coverage|
|Visibility| numerical| The horizontal visibility in KM| --|cloud coverage|
|Air temperature| numerical| Temperature |data correction is need (divide by 10)|hourly data|
|Relative humidity (%)| numerical| Relative humidity in percentage|--|hourly data|
|Sea level pressure| numerical | pressure in hPa|--|hourly data|
|Pressure tendency (hPa)| numerical| The change in pressure with pervious measurement (hPa)|--|hourly data|
|Wind_Direction| numerical| The direction of wind in degree|--|hourly data|
|Wind_Speed| numerical| the velocity of wind in m/s|--|hourly data|
|Wind_gust|numerical| It is the sudden wind increase (m/s)|--|hourly data|
|Precipitation (mm)| numerical |rainfall measurment in mm|--|hourly data|
|Visibility (km)| numerical| The horizontal visibility in KM| duplicate, remove | hourly data|
|Cloud amount (palli)|category| cloud coverage amount |The field got 453125 nan value, will remove|hourly data|
|Station| category | observation location|--|hourly and cloud coverage|
|I_layer_amount| category | measurment in 8 oktas|--|cloud coverage|
|II_layer_amount| category | measurment in 8 oktas|--|cloud coverage|
|III_layer_amount| category | measurment in 8 oktas|--|cloud coverage|
|IV_layer_amount| category | measurment in 8 oktas|--|cloud coverage|
|Present weather| category | Textual description of current weather|remove, can be replace by other columns|cloud coverage| 
|Present weather (sensor)|category | Textual description of current weather|remove, can be replace by other columns|hourly| 
|Present weather (observer)|category | Textual description of current weather|remove, can be replace by other columns|hourly|

In [101]:
hourly_cloudCoverage_join_data_daytime.describe()

,I_layer_height,II_layer_height,III_layer_height,IV_layer_height,Vertical visibility_m,Visibility_km,time2,Air temperature (°C),Relative humidity (%),Sea level pressure (hPa),...,Wind_gust,Cloud amount (palli),Precipitation (mm),Visibility (km),time,Month,date2,date,Sunrise+1,Sunset-1
count,157271.000000,50041.000000,13212.000000,2512.000000,5103.000000,227264.000000,228836.000000,227148.000000,227155.000000,227158.000000,...,215271.000000,9460.000000,227530.000000,227264.000000,228836.000000,228836.000000,228836.000000,228836.000000,228836.000000,228836.000000
mean,1318.342352,2205.924142,2382.712685,2334.251592,1304.425436,254.245578,12.650199,110.411710,74.430424,10127.870121,...,73.241728,7.034778,0.792753,254.245578,317.220525,6.191299,15.755978,15.755978,6.611093,18.689306
std,1484.707225,2280.899832,1707.604284,1763.006148,1657.643732,125.118043,3.939514,81.966672,18.039149,98.319925,...,34.271592,3.514000,5.015318,125.118043,232.353315,2.758785,8.788569,8.788569,1.525671,2.228474
min,30.000000,80.000000,150.000000,210.000000,20.000000,4.000000,5.000000,-281.000000,11.000000,9653.000000,...,0.000000,0.000000,0.000000,4.000000,0.000000,1.000000,1.000000,1.000000,5.000000,14.000000
25%,320.000000,1010.000000,1050.000000,900.000000,70.000000,200.000000,10.000000,46.000000,62.000000,10071.000000,...,49.000000,4.000000,0.000000,200.000000,121.750000,4.000000,8.000000,8.000000,5.000000,17.000000
50%,790.000000,1780.000000,2020.000000,1800.000000,640.000000,200.000000,13.000000,116.000000,78.000000,10137.000000,...,69.000000,9.000000,0.000000,200.000000,259.000000,6.000000,16.000000,16.000000,6.000000,19.000000
75%,1700.000000,2880.000000,3320.000000,3312.500000,1720.000000,350.000000,16.000000,173.000000,89.000000,10191.000000,...,93.000000,10.000000,0.000000,350.000000,551.000000,8.000000,23.000000,23.000000,8.000000,21.000000
max,21500.000000,208100.000000,7490.000000,7510.000000,7250.000000,500.000000,21.000000,343.000000,100.000000,10436.000000,...,312.000000,10.000000,315.000000,500.000000,764.000000,12.000000,31.000000,31.000000,10.000000,21.000000

In [102]:
print(hourly_cloudCoverage_join_data_daytime['I_layer_amount'].unique())
print(hourly_cloudCoverage_join_data_daytime['II_layer_amount'].unique())
print(hourly_cloudCoverage_join_data_daytime['III_layer_amount'].unique())
print(hourly_cloudCoverage_join_data_daytime['IV_layer_amount'].unique())
print(hourly_cloudCoverage_join_data_daytime['Present weather (sensor)'].unique())

['0/8' '1/8' '7/8' '2/8' '6/8' '8/8' '4/8' nan '3/8' '5/8' '-' 'standby'
 'startup']
['0/8' '7/8' '6/8' nan '4/8' '-' '8/8' '5/8' '3/8' '2/8' '1/8']
['0/8' nan '-' '7/8' '3/8' '5/8' '6/8' '2/8' '8/8' '4/8' '1/8']
['0/8' nan '-' '7/8' '6/8' '8/8' '5/8' '4/8' '3/8' '2/8']
['clear' nan 'light snow' 'light rain' 'light rain shower' 'mist' 'fog'
 'drizzle' 'rain' 'moderate rain' 'precipitation' 'light snow shower'
 'heavy rain' 'heavy rain shower' 'moderate rain shower' 'snow'
 'moderate snow' 'heavy snow' 'light rain with snow'
 'moderate or heavy rain with snow' 'moderate snow shower'
 'dizzle or snow grains' 'haze' 'violent rain shower'
 'light or moderate precipitation' 'ice pellets' 'freezing rain' 'shower'
 'freezing drizzle' 'snow grains' 'heavy snow shower' 'ice crystals']

In [177]:
hourly_cloudCoverage_join_data.isna().sum()

Station                            0
I_layer_height                133407
I_layer_amount                  7926
II_layer_height               367305
II_layer_amount                 7932
III_layer_height              443897
III_layer_amount                7934
IV_layer_height               466240
IV_layer_amount                 7935
Vertical visibility_m         457296
Present weather                 3416
Visibility_km                   2748
time2                              0
Date                               0
Air temperature (°C)            3374
Relative humidity (%)           3402
Sea level pressure (hPa)        3366
Pressure tendency (hPa)         4169
Wind_Direction                 28358
Wind_Speed                     27558
Wind_gust                      27937
Cloud amount (palli)          452685
Present weather (sensor)        3416
Present weather (observer)    452509
Precipitation (mm)              2361
Visibility (km)                 2748
time                               0
Month                              0
date2                              0
date                               0
Sunrise+1                          0
Sunset-1                           0
dtype: int64

### Data Cleaning

In [106]:
hourly_cloudCoverage_join_data_daytime

,Station,I_layer_height,I_layer_amount,II_layer_height,II_layer_amount,III_layer_height,III_layer_amount,IV_layer_height,IV_layer_amount,Vertical visibility_m,...,Present weather (sensor),Present weather (observer),Precipitation (mm),Visibility (km),time,Month,date2,date,Sunrise+1,Sunset-1
0,Jõhvi,NaN,0/8,NaN,0/8,NaN,0/8,NaN,0/8,NaN,...,clear,NaN,0.0,200.0,591,5,12,12,5,20
1,Kihnu,NaN,0/8,NaN,0/8,NaN,0/8,NaN,0/8,NaN,...,clear,NaN,0.0,500.0,591,5,12,12,5,20
2,Kunda,NaN,0/8,NaN,0/8,NaN,0/8,NaN,0/8,NaN,...,clear,NaN,0.0,453.0,591,5,12,12,5,20
3,Kuusiku,NaN,0/8,NaN,0/8,NaN,0/8,NaN,0/8,NaN,...,clear,NaN,0.0,200.0,591,5,12,12,5,20
4,Lääne-Nigula,NaN,0/8,NaN,0/8,NaN,0/8,NaN,0/8,NaN,...,clear,NaN,0.0,200.0,591,5,12,12,5,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471936,Viljandi,120.0,8/8,NaN,0/8,NaN,0/8,NaN,0/8,NaN,...,mist,NaN,0.0,44.0,443,12,15,15,10,14
471937,Vilsandi,170.0,8/8,NaN,0/8,NaN,0/8,NaN,0/8,NaN,...,mist,NaN,0.0,56.0,443,12,15,15,10,14
471938,Virtsu,300.0,7/8,NaN,0/8,NaN,0/8,NaN,0/8,NaN,...,clear,NaN,0.0,204.0,443,12,15,15,10,14
471939,Võru,240.0,8/8,NaN,0/8,NaN,0/8,NaN,0/8,NaN,...,clear,NaN,0.0,134.0,443,12,15,15,10,14
471940,Väike-Maarja,70.0,8/8,NaN,0/8,NaN,0/8,NaN,0/8,NaN,...,mist,NaN,0.0,16.0,443,12,15,15,10,14

In [108]:
hourly_cloudCoverage_join_data_daytime=hourly_cloudCoverage_join_data_daytime[hourly_cloudCoverage_join_data_daytime['I_layer_amount'].isna()== False]
hourly_cloudCoverage_join_data_daytime.loc[hourly_cloudCoverage_join_data_daytime['I_layer_amount']=='0/8', 'I_layer_height']=0
hourly_cloudCoverage_join_data_daytime.loc[hourly_cloudCoverage_join_data_daytime['II_layer_amount']=='0/8', 'II_layer_height']=0
hourly_cloudCoverage_join_data_daytime.loc[hourly_cloudCoverage_join_data_daytime['III_layer_amount']=='0/8', 'III_layer_height']=0
hourly_cloudCoverage_join_data_daytime.loc[hourly_cloudCoverage_join_data_daytime['IV_layer_amount']=='0/8', 'IV_layer_height']=0
hourly_cloudCoverage_join_data_daytime['Wind_Speed']=hourly_cloudCoverage_join_data_daytime['Wind_Speed'].fillna(0)
hourly_cloudCoverage_join_data_daytime['Wind_gust']=hourly_cloudCoverage_join_data_daytime['Wind_gust'].fillna(0)
hourly_cloudCoverage_join_data_daytime['Wind_Direction']=hourly_cloudCoverage_join_data_daytime['Wind_Direction'].fillna(-1)
hourly_cloudCoverage_join_data_daytime=hourly_cloudCoverage_join_data_daytime.drop(['Vertical visibility_m','Visibility (km)','Cloud amount (palli)','Present weather','Present weather (observer)','Present weather (observer)'],axis=1)

/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/tmp/ipykernel_597339/3772522951.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hourly_cloudCoverage_join_data_daytime['Wind_Speed']=hourly_cloudCoverage_join_data_daytime['Wind_Speed'].fillna(0)
/tmp/ipykernel_597339/3772522951.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hourly_cloudCoverage_join_data_daytime['Wind_gust']=hourly_cloudCoverage_join_data_daytime['Wind_gust'].fillna(0)
/tmp/ipykernel_597339/3772522951.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hourly_cloudCoverage_join_data_daytime['Wind_Direction']=hourly_cloudCoverage_join_data_daytime['Wind_Direction'].fillna(-1)

In [135]:
hourly_cloudCoverage_join_data_daytime.isna().sum()

Station                        0
I_layer_height               406
I_layer_amount                 0
II_layer_height             1890
II_layer_amount                5
III_layer_height            1890
III_layer_amount               5
IV_layer_height             1890
IV_layer_amount                5
Visibility_km                316
time2                          0
Date                           0
Air temperature (°C)         584
Relative humidity (%)        576
Sea level pressure (hPa)     572
Pressure tendency (hPa)     1118
Wind_Direction                 0
Wind_Speed                     0
Wind_gust                      0
Present weather (sensor)     655
Precipitation (mm)           400
time                           0
Month                          0
date2                          0
date                           0
Sunrise+1                      0
Sunset-1                       0
dtype: int64

In [176]:
# update those row's I_layer_amount to 0/8  (I_layer_amount==nan & PresentWeather==clear)  
hourly_cloudCoverage_join_data_daytime_nofog.loc[hourly_cloudCoverage_join_data_daytime_nofog[(hourly_cloudCoverage_join_data_daytime_nofog['I_layer_height'].isna()==True) & (hourly_cloudCoverage_join_data_daytime_nofog['Present weather (sensor)']=='clear')],'']
#hourly_cloudCoverage_join_data_daytime_nofog.isna().sum()

,Station,I_layer_height,I_layer_amount,II_layer_height,II_layer_amount,III_layer_height,III_layer_amount,IV_layer_height,IV_layer_amount,Visibility_km,...,Wind_Speed,Wind_gust,Present weather (sensor),Precipitation (mm),time,Month,date2,date,Sunrise+1,Sunset-1
8039,Kunda,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,221.0,...,16.0,23.0,clear,0.0,47,11,15,15,9,14
8362,Kunda,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,158.0,...,8.0,36.0,clear,0.0,47,11,15,15,9,14
8590,Kunda,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,190.0,...,5.0,27.0,clear,0.0,47,11,15,15,9,14
14138,Kunda,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,434.0,...,61.0,108.0,clear,0.0,672,8,1,1,6,20
14309,Kunda,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,500.0,...,72.0,115.0,clear,0.0,672,8,1,1,6,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446736,Ruhnu,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,418.0,...,56.0,112.0,clear,0.0,298,7,23,23,5,21
446755,Ruhnu,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,500.0,...,50.0,94.0,clear,0.0,298,7,23,23,5,21
446812,Ruhnu,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,500.0,...,46.0,109.0,clear,0.0,298,7,23,23,5,21
446888,Ruhnu,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,500.0,...,59.0,111.0,clear,0.0,298,7,23,23,5,21
447268,Ruhnu,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,500.0,...,66.0,122.0,clear,0.0,298,7,23,23,5,21

In [172]:
#idx=np.where(hourly_cloudCoverage_join_data['Air temperature (°C)'].isna()==True)[0].tolist()
hourly_cloudCoverage_join_data_daytime_nofog[ ((hourly_cloudCoverage_join_data_daytime_nofog['I_layer_height'].isna()==True) | (hourly_cloudCoverage_join_data_daytime_nofog['II_layer_height'].isna()==True) | (hourly_cloudCoverage_join_data_daytime_nofog['III_layer_height'].isna()==True) ) & (hourly_cloudCoverage_join_data_daytime_nofog['Present weather (sensor)']=='clear')]

,Station,I_layer_height,I_layer_amount,II_layer_height,II_layer_amount,III_layer_height,III_layer_amount,IV_layer_height,IV_layer_amount,Visibility_km,...,Wind_Speed,Wind_gust,Present weather (sensor),Precipitation (mm),time,Month,date2,date,Sunrise+1,Sunset-1
8039,Kunda,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,221.0,...,16.0,23.0,clear,0.0,47,11,15,15,9,14
8362,Kunda,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,158.0,...,8.0,36.0,clear,0.0,47,11,15,15,9,14
8590,Kunda,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,190.0,...,5.0,27.0,clear,0.0,47,11,15,15,9,14
14138,Kunda,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,434.0,...,61.0,108.0,clear,0.0,672,8,1,1,6,20
14309,Kunda,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,500.0,...,72.0,115.0,clear,0.0,672,8,1,1,6,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446736,Ruhnu,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,418.0,...,56.0,112.0,clear,0.0,298,7,23,23,5,21
446755,Ruhnu,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,500.0,...,50.0,94.0,clear,0.0,298,7,23,23,5,21
446812,Ruhnu,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,500.0,...,46.0,109.0,clear,0.0,298,7,23,23,5,21
446888,Ruhnu,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,500.0,...,59.0,111.0,clear,0.0,298,7,23,23,5,21
447268,Ruhnu,NaN,standby,0.0,0/8,0.0,0/8,0.0,0/8,500.0,...,66.0,122.0,clear,0.0,298,7,23,23,5,21

In [54]:
hourly_cloudCoverage_join_data_nofog[hourly_cloudCoverage_join_data_nofog['II_layer_height'].isna()==True]

,Station,I_layer_height,I_layer_amount,II_layer_height,II_layer_amount,III_layer_height,III_layer_amount,IV_layer_height,IV_layer_amount,Visibility_km,...,Air temperature (°C),Relative humidity (%),Sea level pressure (hPa),Pressure tendency (hPa),Wind_Direction,Wind_Speed,Wind_gust,Present weather (sensor),Precipitation (mm),time
541,Sõrve,50.0,-,NaN,-,NaN,-,NaN,-,25.0,...,15.0,100.0,10160.0,1.0,218.0,74.0,103.0,light rain,0.0,544
546,Viljandi,60.0,-,NaN,-,NaN,-,NaN,-,44.0,...,24.0,99.0,10165.0,7.0,243.0,29.0,89.0,light rain,0.0,544
592,Kuusiku,360.0,-,NaN,-,NaN,-,NaN,-,22.0,...,-33.0,91.0,10090.0,9.0,175.0,32.0,66.0,light snow,0.0,492
1086,Kuusiku,330.0,-,NaN,-,NaN,-,NaN,-,24.0,...,-25.0,93.0,9909.0,-29.0,96.0,48.0,95.0,light snow,4.0,61
1814,Sõrve,60.0,-,NaN,-,NaN,-,NaN,-,46.0,...,46.0,100.0,10168.0,-6.0,231.0,103.0,136.0,drizzle,0.0,548
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470202,Sõrve,90.0,-,NaN,-,NaN,-,NaN,-,57.0,...,49.0,100.0,10046.0,6.0,67.0,21.0,32.0,light rain,6.0,86
470466,Ristna,70.0,-,NaN,-,NaN,-,NaN,-,90.0,...,2.0,100.0,10161.0,-1.0,189.0,20.0,54.0,drizzle,1.0,510
470474,Vilsandi,60.0,-,NaN,-,NaN,-,NaN,-,28.0,...,2.0,100.0,10166.0,1.0,201.0,54.0,77.0,light rain shower,0.0,510
470987,Vilsandi,70.0,-,NaN,-,NaN,-,NaN,-,15.0,...,18.0,100.0,10276.0,-8.0,242.0,49.0,81.0,light rain,0.0,54
472001,Kuusiku,210.0,-,NaN,-,NaN,-,NaN,-,93.0,...,-23.0,91.0,10164.0,-7.0,283.0,30.0,58.0,light snow,4.0,506

In [262]:
hourly_cloudCoverage_join_data.iloc[np.where( (hourly_cloudCoverage_join_data['Wind_Speed'].isna()==True))[0]]
hourly_cloudCoverage_join_data.iloc[np.where( (hourly_cloudCoverage_join_data['Wind_Speed'].isna()==True) & (hourly_cloudCoverage_join_data['Wind_Direction'].isna()==False) )[0]]

Empty DataFrame
Columns: [Station, I_layer_height, I_layer_amount, II_layer_height, II_layer_amount, III_layer_height, III_layer_amount, IV_layer_height, IV_layer_amount, Present weather, Visibility_km, time2, Date, Air temperature (°C), Relative humidity (%), Sea level pressure (hPa), Pressure tendency (hPa), Wind_Direction, Wind_Speed, Wind_gust, Present weather (sensor), Visibility (km), time]
Index: []

[0 rows x 23 columns]

/tmp/ipykernel_253032/969121316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hourly_cloudCoverage_join_data['Wind_Speed']=hourly_cloudCoverage_join_data['Wind_Speed'].fillna(0)
/tmp/ipykernel_253032/969121316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hourly_cloudCoverage_join_data['Wind_gust']=hourly_cloudCoverage_join_data['Wind_gust'].fillna(0)
/tmp/ipykernel_253032/969121316.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hourly_cloudCoverage_join_data['Wind_Direction']=hourly_cloudCoverage_join_data['Wind_Direction'].fillna(-1)

In [192]:
hourly_cloudCoverage_join_data.iloc[np.where(hourly_cloudCoverage_join_data['Relative humidity (%)'].isna()==True)[0]]

,Station,I_layer_height,I_layer_amount,II_layer_height,II_layer_amount,III_layer_height,III_layer_amount,IV_layer_height,IV_layer_amount,Present weather,...,Relative humidity (%),Sea level pressure (hPa),Pressure tendency (hPa),Wind_Direction,Wind_Speed,Wind_gust,Present weather (sensor),Precipitation (mm),Visibility (km),time
3087,Sõrve,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,NaN,10075.0,5.0,175.0,53.0,0.0,clear,NaN,275.0,515
3090,Tiirikoja,820.0,8/8,0.0,0/8,0.0,0/8,0.0,0/8,mist,...,NaN,10130.0,4.0,-1.0,0.0,0.0,clear,NaN,200.0,515
13255,Tiirikoja,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,NaN,10126.0,1.0,-1.0,0.0,0.0,clear,NaN,197.0,114
13784,Sõrve,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,NaN,10060.0,-9.0,122.0,84.0,0.0,clear,NaN,232.0,55
13787,Tiirikoja,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,mist,...,NaN,10125.0,-10.0,-1.0,0.0,0.0,mist,NaN,83.0,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313360,Tiirikoja,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,mist,...,NaN,10130.0,4.0,-1.0,0.0,0.0,clear,NaN,200.0,514
318468,Sõrve,1200.0,8/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,NaN,10075.0,5.0,175.0,53.0,0.0,clear,NaN,275.0,515
318471,Tiirikoja,1240.0,7/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,NaN,10130.0,4.0,-1.0,0.0,0.0,clear,NaN,200.0,515
324225,Sõrve,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,NaN,10075.0,5.0,175.0,53.0,0.0,clear,NaN,275.0,515
324228,Tiirikoja,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,mist,...,NaN,10130.0,4.0,-1.0,0.0,0.0,clear,NaN,200.0,515

In [197]:
hourly_cloudCoverage_join_data[hourly_cloudCoverage_join_data['Precipitation (mm)']==0]

,Station,I_layer_height,I_layer_amount,II_layer_height,II_layer_amount,III_layer_height,III_layer_amount,IV_layer_height,IV_layer_amount,Present weather,...,Relative humidity (%),Sea level pressure (hPa),Pressure tendency (hPa),Wind_Direction,Wind_Speed,Wind_gust,Present weather (sensor),Precipitation (mm),Visibility (km),time
0,Jõhvi,410.0,7/8,1280.0,8/8,0.0,0/8,0.0,0/8,clear,...,91.0,10142.0,1.0,153.0,18.0,36.0,clear,0.0,134.0,436
1,Kihnu,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,90.0,10119.0,-8.0,139.0,42.0,78.0,clear,0.0,143.0,436
2,Kunda,370.0,8/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,89.0,10134.0,1.0,146.0,24.0,39.0,clear,0.0,125.0,436
3,Kuusiku,1170.0,7/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,90.0,10125.0,-4.0,148.0,22.0,33.0,clear,0.0,122.0,436
4,Lääne-Nigula,1180.0,7/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,93.0,10116.0,-6.0,136.0,37.0,57.0,clear,0.0,113.0,436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343914,Viljandi,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,75.0,10132.0,-3.0,135.0,23.0,54.0,clear,0.0,166.0,199
343915,Vilsandi,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,76.0,10082.0,-9.0,130.0,55.0,90.0,clear,0.0,318.0,199
343916,Virtsu,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,85.0,10109.0,-6.0,147.0,31.0,74.0,clear,0.0,161.0,199
343917,Võru,0.0,0/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,83.0,10149.0,-4.0,16.0,9.0,14.0,clear,0.0,172.0,199
343918,Väike-Maarja,940.0,7/8,0.0,0/8,0.0,0/8,0.0,0/8,clear,...,89.0,10137.0,0.0,144.0,28.0,38.0,clear,0.0,156.0,199

In [213]:
hourly_cloudCoverage_join_data.iloc[np.where(hourly_cloudCoverage_join_data['Relative humidity (%)'].isna()==True)]

count    334588.000000
mean         93.355655
std          16.745198
min          26.000000
25%          87.000000
50%          95.000000
75%         101.000000
max         138.000000
Name: Air temperature (°C), dtype: float64

In [210]:
hourly_cloudCoverage_join_data.columns

Index(['Station', 'I_layer_height', 'I_layer_amount', 'II_layer_height',
       'II_layer_amount', 'III_layer_height', 'III_layer_amount',
       'IV_layer_height', 'IV_layer_amount', 'Present weather',
       'Visibility_km', 'time2', 'Date', 'Air temperature (°C)',
       'Relative humidity (%)', 'Sea level pressure (hPa)',
       'Pressure tendency (hPa)', 'Wind_Direction', 'Wind_Speed', 'Wind_gust',
       'Present weather (sensor)', 'Visibility (km)', 'time'],
      dtype='object')

In [214]:
data1

,Station,Air temperature (°C),Relative humidity (%),Sea level pressure (hPa),Pressure tendency (hPa),Wind_Direction,Wind_Speed,Wind_gust,Cloud amount (palli),Present weather (sensor),Present weather (observer),Precipitation (mm),Visibility (km),time,Date,time2
0,Heltermaa,96.0,93.0,10115.0,-6.0,151.0,19.0,42.0,NaN,clear,NaN,0.0,211.0,395,01.09.2020,5
1,Jõgeva,88.0,88.0,10139.0,0.0,158.0,11.0,29.0,NaN,clear,NaN,0.0,135.0,395,01.09.2020,5
2,Jõhvi,89.0,90.0,10141.0,3.0,200.0,24.0,39.0,NaN,clear,NaN,0.0,140.0,395,01.09.2020,5
3,Kihnu,97.0,90.0,10127.0,-5.0,162.0,45.0,60.0,NaN,clear,NaN,0.0,139.0,395,01.09.2020,5
4,Kunda,99.0,89.0,10133.0,4.0,210.0,37.0,50.0,NaN,clear,NaN,0.0,163.0,395,01.09.2020,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Valgu,139.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,218,08.03.2020,13
87,Vanaküla,136.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,218,08.03.2020,13
88,Varangu,123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,218,08.03.2020,13
89,Vasknarva,121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,218,08.03.2020,13
90,Vihterpalu,133.0,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,218,08.03.2020,13